apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.app.namespace }}-service"
  namespace: {{ .Values.app.namespace }}

spec:
  selector:
    app.kubernetes.io/name: {{.Values.app.name}}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.containerPort }}
